# CASE STUDY 2: FUEL ECONOMY 


## 1. Import and Explore Data

In [6]:
import pandas as pd
df08=pd.read_csv(r'C:\Users\richtji00\Downloads\all_alpha_08.csv')
df.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no

In [7]:
import pandas as pd
df18=pd.read_csv(r'C:\Users\richtji00\Downloads\all_alpha_18.csv')
df.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no

# Assessing
Use the space below to explore `all_alpha_08.csv` and `all_alpha_18.csv` to answer the quiz questions below.

In [9]:
cnt = df08.count
print(cnt)

<bound method DataFrame.count of             Model  Displ      Cyl    Trans Drive      Fuel Sales Area Stnd  \
0       ACURA MDX    3.7  (6 cyl)  Auto-S5   4WD  Gasoline         CA   U2
1       ACURA MDX    3.7  (6 cyl)  Auto-S5   4WD  Gasoline         FA   B5
2       ACURA RDX    2.3  (4 cyl)  Auto-S5   4WD  Gasoline         CA   U2
3       ACURA RDX    2.3  (4 cyl)  Auto-S5   4WD  Gasoline         FA   B5
4        ACURA RL    3.5  (6 cyl)  Auto-S5   4WD  Gasoline         CA   U2
...           ...    ...      ...      ...   ...       ...        ...  ...
2399  VOLVO XC 90    3.2  (6 cyl)  Auto-S6   4WD  Gasoline         CA   U2
2400  VOLVO XC 90    4.4  (8 cyl)  Auto-S6   4WD  Gasoline         CA   U2
2401  VOLVO XC 90    3.2  (6 cyl)  Auto-S6   2WD  Gasoline         FA   B5
2402  VOLVO XC 90    3.2  (6 cyl)  Auto-S6   4WD  Gasoline         FA   B5
2403  VOLVO XC 90    4.4  (8 cyl)  Auto-S6   4WD  Gasoline         FA   B5

      Underhood ID    Veh Class Air Pollution Score FE Calc Appr City MPG  \
0     8HNXT03.7PKR          SUV                   7          Drv       15
1     8HNXT03.7PKR          SUV                   6          Drv       15
2     8HNXT02.3DKR          SUV                   7          Drv       17
3     8HNXT02.3DKR          SUV                   6          Drv       17
4     8HNXV03.5HKR  midsize car                   7          Drv       16
...            ...          ...                 ...          ...      ...
2399  8VVXB03.2U2N          SUV                   7          Drv       14
2400  8VVXB04.4U2N          SUV                   7          Drv       13
2401  8VVXB03.2U2N          SUV                   6          Drv       14
2402  8VVXB03.2U2N          SUV                   6          Drv       14
2403  8VVXB04.4U2N          SUV                   6          Drv       13

     Hwy MPG Cmb MPG  Unadj Cmb MPG Greenhouse Gas Score SmartWay
0         20      17        22.0527                    4       no
1         20      17        22.0527                    4       no
2         22      19        24.1745                    5       no
3         22      19        24.1745                    5       no
4         24      19        24.5629                    5       no
...      ...     ...            ...                  ...      ...
2399      20      16        20.7134                    4       no
2400      19      15        19.4789                    3       no
2401      20      16        20.9644                    4       no
2402      20      16        20.7134                    4       no
2403      19      15        19.4789                    3       no

[2404 rows x 18 columns]>

In [11]:
df08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2404 entries, 0 to 2403
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 2404 non-null   object
 1   Displ                 2404 non-null   float64
 2   Cyl                   2205 non-null   object
 3   Trans                 2205 non-null   object
 4   Drive                 2311 non-null   object
 5   Fuel                  2404 non-null   object
 6   Sales Area            2404 non-null   object
 7   Stnd                  2404 non-null   object
 8   Underhood ID          2404 non-null   object
 9   Veh Class             2404 non-null   object
 10  Air Pollution Score   2404 non-null   object
 11  FE Calc Appr          2205 non-null   object
 12  City MPG              2205 non-null   object
 13  Hwy MPG               2205 non-null   object
 14  Cmb MPG               2205 non-null   object
 15  Unadj Cmb MPG         2205 non-null   float64
 16  Greenhouse Gas Score  2205 non-null   object
 17  SmartWay              2404 non-null   object
dtypes: float64(2), object(16)
memory usage: 338.2+ KB

In [12]:
df08.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2399    False
2400    False
2401    False
2402    False
2403    False
Length: 2404, dtype: bool

In [13]:
sum(df08.duplicated())

25

In [20]:
print(df18.shape)

(1611, 18)

In [22]:
df18.duplicated()
sum(df18.duplicated())

0

In [34]:
df08.isnull().sum()

Model                     0
Displ                     0
Cyl                     199
Trans                   199
Drive                    93
Fuel                      0
Sales Area                0
Stnd                      0
Underhood ID              0
Veh Class                 0
Air Pollution Score       0
FE Calc Appr            199
City MPG                199
Hwy MPG                 199
Cmb MPG                 199
Unadj Cmb MPG           199
Greenhouse Gas Score    199
SmartWay                  0
dtype: int64

In [26]:
df08.dtypes

Model                    object
Displ                   float64
Cyl                      object
Trans                    object
Drive                    object
Fuel                     object
Sales Area               object
Stnd                     object
Underhood ID             object
Veh Class                object
Air Pollution Score      object
FE Calc Appr             object
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Unadj Cmb MPG           float64
Greenhouse Gas Score     object
SmartWay                 object
dtype: object

In [27]:
df18.dtypes

Model                    object
Displ                   float64
Cyl                     float64
Trans                    object
Drive                    object
Fuel                     object
Cert Region              object
Stnd                     object
Stnd Description         object
Underhood ID             object
Veh Class                object
Air Pollution Score       int64
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Greenhouse Gas Score      int64
SmartWay                 object
Comb CO2                 object
dtype: object

In [28]:
df08.SmartWay.nunique()

2

In [29]:
df18.SmartWay.nunique()

3

In [30]:
df08["Sales Area"].nunique()

3

In [32]:
df18["Cert Region"].nunique()

2

In [33]:
df08["Trans"].nunique()

14

In [37]:
df08.Fuel.unique()

array(['Gasoline', 'ethanol/gas', 'ethanol', 'diesel', 'CNG'],
      dtype=object)

In [38]:
df18.Fuel.unique()

array(['Gasoline', 'Gasoline/Electricity', 'Diesel', 'Ethanol/Gas',
       'Electricity'], dtype=object)

# Cleaning Column Labels
Use `all_alpha_08.csv` and `all_alpha_18.csv`

In [39]:
# drop columns from 2008 dataset
df08.drop(['Stnd', 'Underhood ID', 'FE Calc Appr', 'Unadj Cmb MPG'], axis=1, inplace=True)

# confirm changes
df08.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [43]:
# drop columns from 2018 dataset
df18.drop(['Stnd', 'Stnd Description', 'Underhood ID', 'Comb CO2'], axis=1, inplace=True)

# confirm changes
df18.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No

In [45]:
# rename Sales Area to Cert Region
df08.rename(columns={'Sales Area': 'Cert Region'}, inplace=True)

# confirm changes
df08.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [47]:
# replace spaces with underscores and lowercase labels for 2018 dataset
df18.columns = df18.columns.str.replace(' ','_')

# confirm changes
df18.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No

In [48]:
# replace spaces with underscores and lowercase labels for 2018 dataset
df08.columns = df18.columns.str.replace(' ','_')

# confirm changes
df08.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [49]:
# confirm column labels for 2008 and 2018 datasets are identical
df08.columns == df18.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [51]:
# make sure they're all identical like this
(df08.columns == df18.columns).all()

True

In [53]:
# save new datasets for next section
df08.to_csv('data_08_v1.csv', index=False)
df18.to_csv('data_18_v1.csv', index=False)

# Filter, Drop Nulls, Dedupe
Use `data_08_v1.csv` and `data_18_v1.csv`. You should've created these data files in the previous section: *Cleaning Column Labels*.

In [54]:
# view dimensions of dataset
df08.shape

(2404, 14)

In [55]:
# view dimensions of dataset
df18.shape

(1611, 14)

## Filter by Certification Region

In [56]:
# filter datasets for rows following California standards
df08 = df08.query('Cert_Region == "CA"')
df18 = df18.query('Cert_Region == "CA"')

In [58]:
# confirm only certification region is California
df08['Cert_Region'].unique()

array(['CA'], dtype=object)

In [59]:
# confirm only certification region is California
df18['Cert_Region'].unique()

array(['CA'], dtype=object)

In [62]:
# drop certification region columns form both datasets
df08.drop(columns=['Cert_Region'])
df18.drop(columns=['Cert_Region'])

,Model,Displ,Cyl,Trans,Drive,Fuel,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,small SUV,3,20,28,23,5,No
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,small SUV,3,19,27,22,4,No
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,small car,3,23,33,27,6,No
6,ACURA TLX,3.5,6.0,SemiAuto-9,2WD,Gasoline,small car,3,20,32,24,5,No
8,ACURA TLX,3.5,6.0,SemiAuto-9,4WD,Gasoline,small car,3,21,30,24,5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,VOLVO XC 60,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,small SUV,7,26/60,28/58,26/59,10,Elite
1603,VOLVO XC 90,2.0,4.0,SemiAuto-8,2WD,Gasoline,standard SUV,5,22,29,25,5,No
1605,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,standard SUV,5,22,28,24,5,No
1607,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,standard SUV,5,20,27,23,5,No
1609,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,standard SUV,7,26/63,30/61,27/62,10,Elite

## Drop Rows with Missing Values

In [65]:
# view missing value count for each feature in 2008
df08.isnull().sum()

Model                   0
Displ                   0
Cyl                     0
Trans                   0
Drive                   0
Fuel                    0
Cert_Region             0
Veh_Class               0
Air_Pollution_Score     0
City_MPG                0
Hwy_MPG                 0
Cmb_MPG                 0
Greenhouse_Gas_Score    0
SmartWay                0
dtype: int64

In [66]:
# view missing value count for each feature in 2018
df18.isnull().sum()

Model                   0
Displ                   0
Cyl                     0
Trans                   0
Drive                   0
Fuel                    0
Cert_Region             0
Veh_Class               0
Air_Pollution_Score     0
City_MPG                0
Hwy_MPG                 0
Cmb_MPG                 0
Greenhouse_Gas_Score    0
SmartWay                0
dtype: int64

In [67]:
# drop rows with any null values in both datasets
df08.dropna(inplace=True)
df18.dropna(inplace=True)

In [68]:
# checks if any of columns in 2008 have null values - should print False
df08.isnull().sum().any()

False

In [69]:
# checks if any of columns in 2018 have null values - should print False
df18.isnull().sum().any()

False

## Dedupe Data

In [71]:
# print number of duplicates in 2008 and 2018 datasets
# print number of duplicates in 2008 and 2018 datasets
print(df08.duplicated().sum())
print(df18.duplicated().sum())

23
3

In [72]:
# drop duplicates in both datasets
df08.drop_duplicates(inplace=True)
df18.drop_duplicates(inplace=True)

In [73]:
# print number of duplicates again to confirm dedupe - should both be 0
print(df08.duplicated().sum())
print(df18.duplicated().sum())

0
0

In [74]:
# save progress for the next section
df08.to_csv('data_08_v2.csv', index=False)
df18.to_csv('data_18_v2.csv', index=False)

## Inspecting Data Types

In [76]:
df08.dtypes

Model                    object
Displ                   float64
Cyl                      object
Trans                    object
Drive                    object
Fuel                     object
Cert_Region              object
Veh_Class                object
Air_Pollution_Score      object
City_MPG                 object
Hwy_MPG                  object
Cmb_MPG                  object
Greenhouse_Gas_Score     object
SmartWay                 object
dtype: object

In [77]:
df18.dtypes

Model                    object
Displ                   float64
Cyl                     float64
Trans                    object
Drive                    object
Fuel                     object
Cert_Region              object
Veh_Class                object
Air_Pollution_Score       int64
City_MPG                 object
Hwy_MPG                  object
Cmb_MPG                  object
Greenhouse_Gas_Score      int64
SmartWay                 object
dtype: object

In [79]:
df08.Cyl.unique()

array(['(6 cyl)', '(4 cyl)', '(12 cyl)', '(8 cyl)', '(10 cyl)',
       '(16 cyl)', '(5 cyl)', '(2 cyl)'], dtype=object)

In [80]:
df18.Cyl.unique()

array([ 6.,  4.,  5., 12., 16.,  8.,  3.])

In [82]:
df08.Air_Pollution_Score.unique()

array(['7', '6', '9.5', '9', '6/4'], dtype=object)

In [83]:
df18.Air_Pollution_Score.unique()

array([3, 1, 7, 5, 6], dtype=int64)

In [84]:
df08.Greenhouse_Gas_Score.unique()

array(['4', '5', '6', '7', '0', '1', '3', '2', '8', '9', '10', '7/6'],
      dtype=object)

In [85]:
df18.Greenhouse_Gas_Score.unique()

array([ 5,  4,  6,  7,  2,  1, 10,  3,  9,  8], dtype=int64)

# Fixing `cyl` Data Type
- 2008: extract int from string
- 2018: convert float to int

Load datasets `data_08_v2.csv` and `data_18_v2.csv`. You should've created these data files in the previous section: *Filter, Drop Nulls, Dedupe*.

In [87]:
# check value counts for the 2008 cyl column
df08['Cyl'].value_counts()

(6 cyl)     409
(4 cyl)     283
(8 cyl)     199
(5 cyl)      48
(12 cyl)     30
(10 cyl)     14
(2 cyl)       2
(16 cyl)      1
Name: Cyl, dtype: int64

In [88]:
# Extract int from strings in the 2008 cyl column
df08['Cyl'] = df08['Cyl'].str.extract('(\d+)').astype(int)

In [89]:
df08.dtypes

Model                    object
Displ                   float64
Cyl                       int32
Trans                    object
Drive                    object
Fuel                     object
Cert_Region              object
Veh_Class                object
Air_Pollution_Score      object
City_MPG                 object
Hwy_MPG                  object
Cmb_MPG                  object
Greenhouse_Gas_Score     object
SmartWay                 object
dtype: object

In [90]:
# Check value counts for 2008 cyl column again to confirm the change
df08['Cyl'].value_counts()

6     409
4     283
8     199
5      48
12     30
10     14
2       2
16      1
Name: Cyl, dtype: int64

In [92]:
df18['Cyl'].value_counts()

4.0     365
6.0     246
8.0     153
3.0      18
12.0      9
5.0       2
16.0      1
Name: Cyl, dtype: int64

In [93]:
df18['Cyl'] = df18['Cyl'].astype(int)

In [94]:
df18['Cyl'].value_counts()

4     365
6     246
8     153
3      18
12      9
5       2
16      1
Name: Cyl, dtype: int64

# Fixing `air_pollution_score` Data Type
- 2008: convert string to float
- 2018: convert int to float

Load datasets `data_08_v3.csv` and `data_18_v3.csv`. You should've created these data files in the previous section: *Fixing Data Types Pt 1*.

In [95]:
# try using pandas' to_numeric or astype function to convert the
# 2008 air_pollution_score column to float -- this won't work

# Figuring out the issue
Looks like this isn't going to be as simple as converting the datatype. According to the error above, the air pollution score value in one of the rows is "6/4" - let's check it out.

In [96]:
df08[df08.Air_Pollution_Score == '6/4']

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
1550,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol/gas,CA,small car,6/4,13/18,19/25,15/21,7/6,no

# It's not just the air pollution score!
The mpg columns and greenhouse gas scores also seem to have the same problem - maybe that's why these were all saved as strings! According to [this link](http://www.fueleconomy.gov/feg/findacarhelp.shtml#airPollutionScore), which I found from the PDF documentation:

    "If a vehicle can operate on more than one type of fuel, an estimate is provided for each fuel type."
    
Ohh... so all vehicles with more than one fuel type, or hybrids, like the one above (it uses ethanol AND gas) will have a string that holds two values - one for each. This is a little tricky, so I'm going to show you how to do it with the 2008 dataset, and then you'll try it with the 2018 dataset.

In [97]:
# First, let's get all the hybrids in 2008
hb08 = df08[df08['Fuel'].str.contains('/')]
hb08

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
1550,MERCEDES-BENZ C300,3.0,6,Auto-L7,2WD,ethanol/gas,CA,small car,6/4,13/18,19/25,15/21,7/6,no

Looks like this dataset only has one! The 2018 has MANY more - but don't worry - the steps I'm taking here will work for that as well!

In [98]:
# hybrids in 2018
hb18 = df18[df18['Fuel'].str.contains('/')]
hb18

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
108,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,3,28/66,34/78,30/71,10,Yes
160,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,7,27/70,31/75,29/72,10,Elite
162,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,small car,7,27/66,31/68,28/67,10,Elite
188,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,large car,3,25/62,29/68,27/64,9,Yes
382,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol/Gas,CA,large car,5,14/18,20/28,16/22,4,No
394,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol/Gas,CA,pickup,5,12/18,16/24,14/20,4,No
396,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol/Gas,CA,pickup,5,12/17,15/22,13/19,3,No
398,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,pickup,3,12/16,17/23,14/19,3,No
428,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
432,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,15/22,12/18,3,No
436,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
440,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,16/22,13/18,3,No
454,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,CA,small car,3,43/113,42/99,42/106,10,Yes
456,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,CA,small car,7,43/113,42/99,42/106,10,Elite
458,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol/Gas,CA,large car,3,14/19,22/30,17/23,5,No
462,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol/Gas,CA,large car,3,13/18,20/27,16/21,4,No
492,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol/Gas,CA,large car,3,14/19,22/30,17/23,5,No
496,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol/Gas,CA,large car,3,13/18,20/27,16/21,4,No
605,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline/Electricity,CA,midsize car,7,43/102,41/91,42/97,10,Elite
659,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol/Gas,CA,pickup,5,12/18,16/24,14/20,4,No
661,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol/Gas,CA,pickup,5,12/17,15/22,13/19,3,No
663,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,pickup,3,12/16,17/23,14/19,3,No
697,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
701,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,16/22,13/18,3,No
709,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
715,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,15/22,12/18,3,No
892,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol/Gas,CA,small SUV,3,15/21,22/30,18/25,5,No
896,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol/Gas,CA,small SUV,3,14/21,21/28,17/23,5,No
933,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline/Electricity,CA,small car,1,20/59,21/61,20/60,10,No
1162,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,CA,small car,5,17/24,24/32,20/27,6,No
1179,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,CA,small SUV,5,17/23,23/31,19/26,5,No
1192,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Ethanol/Gas,CA,standard SUV,3,13/18,17/22,14/19,3,No
1256,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Gasoline/Electricity,CA,midsize car,3,28/63,27/66,27/65,9,Yes
1507,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,CA,standard SUV,5,9/13,13/17,10/14,1,No
1517,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,CA,pickup,5,9/13,12/17,10/15,2,No
1577,VOLVO S90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,midsize car,7,26/70,33/72,29/71,10,Elite
1601,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,small SUV,7,26/60,28/58,26/59,10,Elite
1609,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite

We're going to take each hybrid row and split them into two new rows - one with values for the first fuel type (values before the "/"), and the other with values for the second fuel type (values after the "/"). Let's separate them with two dataframes!

In [103]:
# create two copies of the 2008 hybrids dataframe
df1 = hb08.copy()  # data on first fuel type of each hybrid vehicle
df2 = hb18.copy()  # data on second fuel type of each hybrid vehicle

# Each one should look like this
df2

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert_Region,Veh_Class,Air_Pollution_Score,City_MPG,Hwy_MPG,Cmb_MPG,Greenhouse_Gas_Score,SmartWay
108,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,3,28/66,34/78,30/71,10,Yes
160,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,7,27/70,31/75,29/72,10,Elite
162,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,small car,7,27/66,31/68,28/67,10,Elite
188,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,large car,3,25/62,29/68,27/64,9,Yes
382,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol/Gas,CA,large car,5,14/18,20/28,16/22,4,No
394,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol/Gas,CA,pickup,5,12/18,16/24,14/20,4,No
396,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol/Gas,CA,pickup,5,12/17,15/22,13/19,3,No
398,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,pickup,3,12/16,17/23,14/19,3,No
428,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
432,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,15/22,12/18,3,No
436,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
440,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,16/22,13/18,3,No
454,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,CA,small car,3,43/113,42/99,42/106,10,Yes
456,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,CA,small car,7,43/113,42/99,42/106,10,Elite
458,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol/Gas,CA,large car,3,14/19,22/30,17/23,5,No
462,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol/Gas,CA,large car,3,13/18,20/27,16/21,4,No
492,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol/Gas,CA,large car,3,14/19,22/30,17/23,5,No
496,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol/Gas,CA,large car,3,13/18,20/27,16/21,4,No
605,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline/Electricity,CA,midsize car,7,43/102,41/91,42/97,10,Elite
659,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol/Gas,CA,pickup,5,12/18,16/24,14/20,4,No
661,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol/Gas,CA,pickup,5,12/17,15/22,13/19,3,No
663,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,pickup,3,12/16,17/23,14/19,3,No
697,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
701,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,16/22,13/18,3,No
709,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol/Gas,CA,standard SUV,3,12/16,17/23,14/19,3,No
715,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,CA,standard SUV,3,11/16,15/22,12/18,3,No
892,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol/Gas,CA,small SUV,3,15/21,22/30,18/25,5,No
896,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol/Gas,CA,small SUV,3,14/21,21/28,17/23,5,No
933,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline/Electricity,CA,small car,1,20/59,21/61,20/60,10,No
1162,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,CA,small car,5,17/24,24/32,20/27,6,No
1179,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,CA,small SUV,5,17/23,23/31,19/26,5,No
1192,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Ethanol/Gas,CA,standard SUV,3,13/18,17/22,14/19,3,No
1256,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Gasoline/Electricity,CA,midsize car,3,28/63,27/66,27/65,9,Yes
1507,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,CA,standard SUV,5,9/13,13/17,10/14,1,No
1517,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,CA,pickup,5,9/13,12/17,10/15,2,No
1577,VOLVO S90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,midsize car,7,26/70,33/72,29/71,10,Elite
1601,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,small SUV,7,26/60,28/58,26/59,10,Elite
1609,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite

For this next part, we're going use pandas' apply function. See the docs [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html).

In [108]:
# columns to split by "/"
split_columns = ['Fuel', 'Air_Pollution_Score', 'City_MPG', 'Hwy_MPG', 'Cmb_MPG', 'Greenhouse_Gas_Score']

# apply split function to each column of each dataframe copy
for c in split_columns:
    df1[c] = df1[c].apply(lambda x: x.split("/")[0])
    df2[c] = df2[c].apply(lambda x: x.split("/")[1])

AttributeError: 'int' object has no attribute 'split'

In [107]:
MyList = ["item1", "item2"]
print(MyList[0]) # Will work
print(MyList[1]) # Will Work
print(MyList[2]) # Will crash.

item1
item2

IndexError: list index out of range